version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/deploy
    overwrite: yes

hooks:
#  ApplicationStop:
#    - location: scripts/stopDocker.sh
#      timeout: 60
#      runas: root
  BeforeInstall:
    - location: scripts/pullDocker.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/runDocker.sh
      timeout: 60
      runas: root
