version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/deploy
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 120
      runas: root

