version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/deploy
file_exists_behavior: OVERWRITE

hooks:
#  BeforeInstall:
#    - location: scripts/stopDocker.sh
#      timeout: 120
#      runas: root
  AfterInstall:
    - location: scripts/pullDocker.sh
      timeout: 120
      runas: root
#  ApplicationStart:
#    - location: scripts/runDocker.sh
#      timeout: 60
#      runas: root
