version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - echo $IMAGE_REPO_NAME
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Pulling Docker Images for cache...
      - docker images
      - docker-compose pull --ignore-pull-failures -q
#      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - docker images
      - docker build -t was .
  post_build:
    commands:
      - echo Build started on `date`
      - echo Pushing Docker image to ECR...
      - docker images
      - docker tag was:latest was:latest
      - docker tag mariadb:10 mariadb:10
      - docker tag nginx:latest nginx:latest
      - docker-compose -f docker-compose.yml push
      - docker push was:latest
      - docker push mariadb:10
      - docker push nginx:latest
      - docker images
