version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws --version
      - cat dockerfile
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Pulling Docker Images for cache...
      - docker images
#      - docker-compose pull --ignore-pull-failures -q
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build -t was . --build-arg JA_SECRET="$JA_SECRET"
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - docker tag was:latest $REPOSITORY_URI:latest
      - docker images
      - docker push $REPOSITORY_URI:latest
      - docker images
artifacts:
  files:
    - "appspec.yml"
    - "scripts/*"
    - "docker-compose.yml"
