version: "3"
services:

  # Database : mariaDB
  mariaDB:
    platform: linux/x86_64
    image: mariadb:10
#    image: public.ecr.aws/docker/library/mariadb:latest
    container_name: photo_mariadb
    ports:
      - 3306:3306
    restart: always
    environment:
      TZ: Asia/Seoul
      MARIADB_DATABASE: photogram
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_USER: seung
      MARIADB_PASSWORD: 1234
    volumes:
      - /home/ubuntu/backup/data/mysql:/var/lib/mysql
#      - /Users/euseung/Documents/dev/cloneCoding/photogram/instagram/docker/data/mysql:/var/lib/mysql


  # was : Spring Boot
  was:
    container_name: photo_backend
    restart: always
#    build: ./
    image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
#    image: 076796029005.dkr.ecr.ap-northeast-2.amazonaws.com/photo-ecr:latest
    expose:
      - 8080
    depends_on:
      - mariaDB

  # web server : nginx
  web:
    image: nginx
#    image: public.ecr.aws/nginx/nginx:latest
    container_name: photo_nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - was

#
# docker-compose -f docker-compose.yml up -d
# docker-compose -f docker-compose.yml down